=== tfreese/maven-proxy/proxy-config/src/main/resources/xsd/proxy-config.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- https://www.w3schools.com/xml/schema_intro.asp -->

<!--<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://github.com/tfreese/maven-proxy/config"
           targetNamespace="http://github.com/tfreese/maven-proxy/config"
           attributeFormDefault="unqualified"
           elementFormDefault="qualified"
>

    <!--    <import schemaLocation="baseTypes.xsd" namespace="http://baseTypes" />-->

    <xs:element name="proxy-config">
        <xs:annotation>
            <xs:documentation source="description">Configuration for the Maven-Proxy.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="port" type="ProxyPort" />
                <xs:element name="repositories" type="Repositories" />
                <xs:element name="file-cache" type="FileCache" minOccurs="0" />
                <xs:element name="db-monitoring" type="DbMonitoring" minOccurs="0" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="ProxyPort">
        <xs:annotation>
            <xs:documentation source="description">Port for the Maven-Proxy [1025-65534].</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:positiveInteger">
            <xs:minExclusive value="1024" />
            <xs:maxExclusive value="65535" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="FileUri">
        <xs:annotation>
            <xs:documentation source="description">file://*</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:anyURI">
            <xs:minLength value="10" />
            <xs:pattern value="file://.*" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="RemoteUri">
        <xs:annotation>
            <xs:documentation source="description">http://*, https://</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:anyURI">
            <xs:minLength value="10" />
            <xs:pattern value="http://.*" />
            <xs:pattern value="https://.*" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="LocalRepo">
        <xs:annotation>
            <xs:documentation source="description">
                Local file Repository for deployments [file://*].
                Like: deploy-releases, deploy-snapshots, deploy-sites
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="name" type="xs:normalizedString" />
            <xs:element name="path" type="FileUri" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="RemoteRepo">
        <xs:annotation>
            <xs:documentation source="description">Remote Repository for Dependencies [http://*,https://*].</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="name" type="xs:normalizedString" />
            <xs:element name="url" type="RemoteUri" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="VirtualRepo">
        <xs:annotation>
            <xs:documentation source="description">
                Virtual Repository as mirror for maven [http://HOST:PORT/NAME]
                Processed in declarative order.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="name" type="xs:normalizedString" />
            <xs:element name="repository-name" type="xs:normalizedString" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Repositories">
        <xs:annotation>
            <xs:documentation source="description">Repository Declaration.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="remote" type="RemoteRepo" maxOccurs="unbounded" />
            <xs:element name="local" type="LocalRepo" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="virtual" type="VirtualRepo" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="FileCache">
        <xs:annotation>
            <xs:documentation source="description">Local Cache for remote Repositories.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="local-url" type="FileUri">
                <xs:annotation>
                    <xs:documentation source="description">File Url for Cache [file://*]</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="enabled" type="xs:boolean" use="required">
            <xs:annotation>
                <xs:documentation source="description">Enable/Disable this service.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="DbMonitoring">
        <xs:annotation>
            <xs:documentation source="description">DB-Monitoring for the Maven-Proxy.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="jdbc-url">
                <xs:simpleType>
                    <xs:restriction base="xs:normalizedString">
                        <xs:minLength value="10" />
                        <xs:pattern value="jdbc:.*" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="enabled" type="xs:boolean" use="required">
            <xs:annotation>
                <xs:documentation source="description">Enable/Disable this service.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <!--    <xs:simpleType name="RepositoryUri">-->
    <!--        <xs:annotation>-->
    <!--            <xs:documentation source="description">file://*, http://*, https://*</xs:documentation>-->
    <!--        </xs:annotation>-->
    <!--        &lt;!&ndash;        <xs:restriction base="xs:anyURI">&ndash;&gt;-->
    <!--        &lt;!&ndash;            <xs:pattern value="file://.*" />&ndash;&gt;-->
    <!--        &lt;!&ndash;            <xs:pattern value="http://.*" />&ndash;&gt;-->
    <!--        &lt;!&ndash;            <xs:pattern value="https://.*" />&ndash;&gt;-->
    <!--        &lt;!&ndash;        </xs:restriction>&ndash;&gt;-->
    <!--        <xs:union memberTypes="FileUri">-->
    <!--            <xs:simpleType>-->
    <!--                <xs:restriction base="xs:anyURI">-->
    <!--                    <xs:minLength value="10"/>-->
    <!--                    <xs:pattern value="http://.*"/>-->
    <!--                    <xs:pattern value="https://.*"/>-->
    <!--                </xs:restriction>-->
    <!--            </xs:simpleType>-->
    <!--        </xs:union>-->
    <!--    </xs:simpleType>-->

</xs:schema>

=== tfreese/maven-proxy/proxy-main/proxy-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- https://www.w3schools.com/xml/schema_intro.asp -->

<!--<proxy-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="proxy-config.xsd">-->

<proxy-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://github.com/tfreese/maven-proxy/config"
              xsi:schemaLocation="http://github.com/tfreese/maven-proxy/config https://raw.githubusercontent.com/tfreese/maven-proxy/master/proxy-main/proxy-config.xml">

    <server-config>
        <port>7999</port>
        <thread-pool-core-size>2</thread-pool-core-size>
        <thread-pool-max-size>6</thread-pool-max-size>
        <thread-name-pattern>http-server-%d</thread-name-pattern>
    </server-config>

    <client-config>
        <thread-pool-core-size>2</thread-pool-core-size>
        <thread-pool-max-size>6</thread-pool-max-size>
        <thread-name-pattern>http-client-%d</thread-name-pattern>
    </client-config>

    <repositories>
        <remote>
            <name>maven-central</name>
            <url>https://repo1.maven.org/maven2</url>
        </remote>
        <remote>
            <name>spring-release</name>
            <url>https://repo.spring.io/release</url>
        </remote>
        <remote>
            <name>primefaces</name>
            <url>https://repository.primefaces.org</url>
        </remote>
        <remote>
            <name>gradle-releases</name>
            <url>https://repo.gradle.org/gradle/libs-releases</url>
        </remote>
        <remote>
            <name>gradle-plugins</name>
            <url>https://plugins.gradle.org/m2</url>
        </remote>
        <local>
            <name>third-party</name>
            <path>file:///tmp/maven-proxy/third-party</path>
        </local>
        <local writeable="true">
            <name>deploy-releases</name>
            <path>file:///tmp/maven-proxy/deploy-releases</path>
        </local>
        <local writeable="true">
            <name>deploy-snapshots</name>
            <path>file:///tmp/maven-proxy/deploy-snapshots</path>
        </local>
        <local writeable="true">
            <name>deploy-sites</name>
            <path>file:///tmp/maven-proxy/deploy-sites</path>
        </local>
        <virtual>
            <name>public</name>
            <repository-name>third-party</repository-name>
            <repository-name>maven-central</repository-name>
            <repository-name>spring-release</repository-name>
            <repository-name>primefaces</repository-name>
            <repository-name>gradle-releases</repository-name>
            <repository-name>gradle-plugins</repository-name>
            <repository-name>deploy-releases</repository-name>
            <repository-name>deploy-snapshots</repository-name>
        </virtual>
        <virtual>
            <name>public-local</name>
            <repository-name>third-party</repository-name>
            <repository-name>deploy-releases</repository-name>
            <repository-name>deploy-snapshots</repository-name>
        </virtual>
    </repositories>

    <file-cache enabled="true">
        <local-url>file:///tmp/maven-proxy/cache</local-url>
    </file-cache>

    <db-monitoring enabled="false">
        <jdbc-url>jdbc:string</jdbc-url>
    </db-monitoring>

</proxy-config>
